---
- name: Gather and display system information
  hosts: all
  gather_facts: true

  tasks:
    - name: Display basic system information
      debug:
        msg:
          - "Hostname: {{ ansible_hostname }}"
          - "OS Family: {{ ansible_os_family }}"
          - "Distribution: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "Architecture: {{ ansible_architecture }}"
          - "CPU Count: {{ ansible_processor_vcpus }}"
          - "Memory Total (MB): {{ ansible_memtotal_mb }}"
          - "IP Address: {{ ansible_default_ipv4.address }}"
