---
- name: converge
  hosts: [cluster.controll_plane, cluster.workers]
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.roles.consul
      consul_bootstrap_expect: 1
      consul_encrypt: "{{ CONSUL_ENCRYPT }}"
      consul_bind_addr: "0.0.0.0"
