---
- name: Prepare
  hosts: [cluster.controll_plane, cluster.workers]
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp
